-- ==========================================================================
-- TrueAnchor — devotional content seed
--
-- GENERATED by tool/build_devotional_seed.dart — do not edit by hand.
-- Source: content/devotionals (5 files)
--
-- Idempotent on publish_on: re-running updates existing rows in place rather
-- than duplicating them, so this is safe to paste as often as content changes.
-- Requires app_admin (devotionals_insert) or the SQL Editor's elevated role.
-- ==========================================================================

begin;

insert into public.devotionals
  (publish_on, title, scripture_reference, scripture_text, translation,
   copyright_notice, body, discussion_questions, activity)
values
  (
    '2026-07-27',
    $ta$An Anchor for the Soul$ta$,
    $ta$Hebrews 6:19-20$ta$,
    $ta$This hope we have as an anchor of the soul, a hope both sure and steadfast and entering into that which is within the veil, where as a forerunner Jesus entered for us.$ta$,
    $ta$WEB$ta$,
    null,
    $ta$An anchor is a strange thing to hope in. It is heavy, unlovely, and it spends its whole life out of sight. Nobody photographs the anchor. But in a storm it is the only part of the boat that matters, because it is the one part that is not moving.

The writer of Hebrews had been talking to people who were tired. They had believed, and then life had gone on being difficult, and they were starting to wonder whether they had misheard God somewhere along the way. He does not answer them with advice. He answers them with a picture: your hope is already fastened to something, and it is fastened on the other side of the veil, where Jesus has already gone.

That is the part worth sitting with. The anchor does not hold because you are gripping it hard enough. It holds because of what it is attached to. On the days your faith feels thin, the rope may be fraying in your hands, but the thing on the far end has not moved an inch.

You will have weeks this year when you feel like you are drifting. Drifting is not the same as being adrift.$ta$,
    array[$ta$Where do you feel unsteady right now?$ta$, $ta$What is your hope actually attached to — an outcome, a person, or Christ?$ta$, $ta$What would change this week if you believed the anchor was holding even when you could not feel it?$ta$]::text[],
    $ta$Write one sentence in your journal naming the storm you are in. Then write one sentence naming what is holding you.$ta$
  ),
  (
    '2026-07-28',
    $ta$Made to Lie Down$ta$,
    $ta$Psalm 23:1-3$ta$,
    $ta$Yahweh is my shepherd; I shall lack nothing. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul.$ta$,
    $ta$WEB$ta$,
    null,
    $ta$"He makes me lie down." Not invites. Not suggests. Makes.

Sheep will not lie down when they are anxious. A shepherd who wants a resting flock has to deal with whatever is frightening them first — the predator in the treeline, the flies, the quarrel between two animals at the edge of the group. The rest is not laziness. It is evidence that someone competent is standing watch.

Most of us do not have a resting problem. We have a trust problem that shows up as a resting problem. We keep the phone in our hand at midnight because putting it down feels like letting go of the wheel. And then we are surprised that our soul feels thin.

David had been a shepherd before he was a king. He knew that a sheep lying down in good grass beside quiet water is a sheep that has stopped scanning the horizon, because it has learned the horizon is being watched by someone else.

Your soul gets restored in the lying down, not in the running. That is not a reward for finishing everything. It is how you were built.$ta$,
    array[$ta$What are you scanning the horizon for right now?$ta$, $ta$What would it look like, practically, to let God stand watch over that today?$ta$, $ta$When did you last rest without feeling guilty about it?$ta$]::text[],
    $ta$Pick one hour today with no screen in it. Spend ten minutes of it doing nothing at all.$ta$
  ),
  (
    '2026-07-29',
    $ta$Tell Him the Actual Thing$ta$,
    $ta$Philippians 4:6-7$ta$,
    $ta$In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.$ta$,
    $ta$WEB$ta$,
    null,
    $ta$Paul wrote this from a prison cell, which is worth knowing before you decide he was being glib.

"Let your requests be made known to God" is a plainer instruction than we usually treat it. Not your tidied-up requests. Not the version you would be comfortable praying out loud in a group. The actual thing — the audition, the diagnosis, the friendship that has gone quiet, the sin you have not said out loud to anyone.

God already knows it. The telling is not for His information. It is for you: naming a fear to God is how it stops being a shapeless weight and becomes a specific thing that a specific Person is now holding with you.

Notice what Paul promises and what he does not. He does not promise you will get what you asked for. He promises peace that guards you — a garrison word, a soldier posted at the gate of your thinking. The circumstances may not move. The thing standing between you and panic will.

So be specific today. Vague prayers are hard to see answered.$ta$,
    array[$ta$What is the one thing you have not actually told God about?$ta$, $ta$Why is thanksgiving in the same sentence as anxiety here?$ta$, $ta$What would peace 'guarding your thoughts' look like in your week?$ta$]::text[],
    $ta$Write down three specific requests and one thing you are thankful for. Keep the page — come back to it in a month.$ta$
  ),
  (
    '2026-07-30',
    $ta$First, Not Only$ta$,
    $ta$Matthew 6:33$ta$,
    $ta$But seek first God's Kingdom and his righteousness; and all these things will be given to you as well.$ta$,
    $ta$WEB$ta$,
    null,
    $ta$Jesus had just spent several minutes talking about clothes and food and birds. It is a surprisingly ordinary passage. He is not telling worried people to care about nothing; He is telling them He knows exactly what they are worried about, down to the grocery list.

And then: seek first. Not seek only. Following Jesus does not mean your grades, your team, your job and your friendships stop mattering. It means they stop being first. There is only one first, and whatever occupies it quietly organizes everything else.

The test is not what you say matters most. The test is what your calendar and your attention already answer. Where does your mind go the second it is unoccupied? That is a more honest answer than anything you would write down.

Rearranging that order is not one dramatic decision. It is a hundred small ones — what you do with the first ten minutes of the morning, whether you open the passage before the feed, whether you tell the truth when a lie would be easier.

Seek first. The rest is being handled.$ta$,
    array[$ta$If someone looked only at your week, what would they say is first?$ta$, $ta$What is one thing that has quietly moved into first place?$ta$, $ta$What is the smallest change that would put God's Kingdom back at the front of your day?$ta$]::text[],
    $ta$Tomorrow morning, open Scripture before you open anything else. Notice how hard or easy that was.$ta$
  ),
  (
    '2026-07-31',
    $ta$Courage Is a Command$ta$,
    $ta$Joshua 1:9$ta$,
    $ta$Haven't I commanded you? Be strong and courageous. Don't be afraid. Don't be dismayed, for Yahweh your God is with you wherever you go.$ta$,
    $ta$WEB$ta$,
    null,
    $ta$Joshua was taking over from Moses. Moses, who had parted a sea. Every person Joshua was about to lead had spent forty years watching someone else do the job he was now expected to do.

God tells him to be courageous three times in nine verses. You do not repeat yourself to someone who is already fine.

What is strange is that courage is given as a command. We usually treat bravery as a temperament — some people have it, most of us watch them. But a command implies it is something you can obey whether or not you feel it. Courage here is not the absence of fear; it is moving anyway, because of a fact you have decided to believe: your God is with you wherever you go.

Notice the reason God gives. Not "because you are ready." Not "because it will work out." Because I am with you. The courage is borrowed. It always was.

There is something this week you have been putting off because you are afraid of it — a conversation, an apology, an honest answer. You will probably still be afraid when you do it. Do it afraid.$ta$,
    array[$ta$What have you been avoiding because you are afraid of it?$ta$, $ta$How is courage different from confidence?$ta$, $ta$What changes if 'God is with you' is a fact rather than a feeling?$ta$]::text[],
    $ta$Name the thing you have been avoiding. Do one step of it today — even just sending the first message.$ta$
  )
on conflict (publish_on) do update set
  title                = excluded.title,
  scripture_reference  = excluded.scripture_reference,
  scripture_text       = excluded.scripture_text,
  translation          = excluded.translation,
  copyright_notice     = excluded.copyright_notice,
  body                 = excluded.body,
  discussion_questions = excluded.discussion_questions,
  activity             = excluded.activity,
  updated_at           = now();

commit;
